// apps/demos/src/pinia/Runtime.vue
<script setup lang="ts">
import { useLikftc } from "@vp-tw/likftc/vue";
import { storeToRefs } from "pinia";
import { computed } from "vue";

import {
  createAfterRows,
  createBeforeRows,
  describeRow,
  type DemoRenderedRow,
} from "../shared/demo.js";
import { useDemoStore } from "../state/stores/pinia.js";

const { frame } = storeToRefs(useDemoStore());
const entries = useLikftc(() => frame.value.items, { getId: (item) => item.id });
const beforeRows = computed(() => createBeforeRows(frame.value));
const afterRows = computed(() => createAfterRows(frame.value, entries.value));

const rowPhase = (row: DemoRenderedRow): "current" | "exiting" =>
  row.kind === "exiting" ? "exiting" : "current";
</script>

<template>
  <div class="runtime-grid">
    <article class="runtime-panel">
      <small>WITHOUT + PINIA</small>
      <h3>Logical ID key</h3>
      <ol data-list="before">
        <li
          v-for="row in beforeRows"
          :key="row.key"
          class="runtime-row"
          :data-collision="String(row.kind === 'collision')"
          :data-id="row.item.id"
          :data-key="row.keyText"
          :data-kind="row.kind"
          :data-phase="rowPhase(row)"
          :data-slot="String(row.slot)"
        >
          <b>{{ row.item.id.toUpperCase() }}</b>
          <span>{{ row.item.label }}</span>
          <code>{{ row.keyText }}</code>
          <em>{{ describeRow(row.kind) }}</em>
        </li>
      </ol>
    </article>
    <article class="runtime-panel">
      <small>WITH LIKFTC + PINIA</small>
      <h3>Presence identity</h3>
      <ol data-list="after">
        <li
          v-for="row in afterRows"
          :key="row.key"
          class="runtime-row"
          :data-collision="String(row.kind === 'collision')"
          :data-id="row.item.id"
          :data-key="row.keyText"
          :data-kind="row.kind"
          :data-phase="rowPhase(row)"
          :data-slot="String(row.slot)"
        >
          <b>{{ row.item.id.toUpperCase() }}</b>
          <span>{{ row.item.label }}</span>
          <code>{{ row.keyText }}</code>
          <em>{{ describeRow(row.kind) }}</em>
        </li>
      </ol>
    </article>
  </div>
</template>

// apps/demos/src/svelte/Runtime.svelte
<script lang="ts">
  import { createLikftc } from "@vp-tw/likftc/svelte";
  import { untrack } from "svelte";
  import { derived, type Readable } from "svelte/store";

  import {
    createAfterRows,
    createBeforeRows,
    type DemoFrameState,
  } from "../shared/demo.js";
  import Row from "./Row.svelte";

  let { frame }: { frame: Readable<DemoFrameState> } = $props();

  const items = untrack(() => derived(frame, (state) => state.items));
  const entries = untrack(() => createLikftc(items, { getId: (item) => item.id }));
  let beforeRows = $derived(createBeforeRows($frame));
  let afterRows = $derived(createAfterRows($frame, $entries));
</script>

<div class="runtime-grid">
  <article class="runtime-panel">
    <small>WITHOUT</small>
    <h3>Logical ID key</h3>
    <ol data-list="before">
      {#each beforeRows as row (row.key)}
        <Row {row} />
      {/each}
    </ol>
  </article>
  <article class="runtime-panel">
    <small>WITH @LIKFTC/SVELTE</small>
    <h3>Presence identity</h3>
    <ol data-list="after">
      {#each afterRows as row (row.key)}
        <Row {row} />
      {/each}
    </ol>
  </article>
</div>
