// apps/demos/src/vue/Runtime.vue
<script setup lang="ts">
import { useLikftc } from "@vp-tw/likftc/vue";
import { computed, type ShallowRef } from "vue";

import { createAfterRows, createBeforeRows, type DemoFrameState } from "../shared/demo.js";
import Row from "./Row.vue";

const props = defineProps<{ readonly frame: ShallowRef<DemoFrameState> }>();
const entries = useLikftc(() => props.frame.value.items, { getId: (item) => item.id });
const beforeRows = computed(() => createBeforeRows(props.frame.value));
const afterRows = computed(() => createAfterRows(props.frame.value, entries.value));
</script>

<template>
  <div class="runtime-grid">
    <article class="runtime-panel">
      <small>WITHOUT</small>
      <h3>Logical ID key</h3>
      <ol data-list="before">
        <Row v-for="row in beforeRows" :key="row.key" :row />
      </ol>
    </article>
    <article class="runtime-panel">
      <small>WITH @LIKFTC/VUE</small>
      <h3>Presence identity</h3>
      <ol data-list="after">
        <Row v-for="row in afterRows" :key="row.key" :row />
      </ol>
    </article>
  </div>
</template>

// apps/demos/src/svelte/Runtime.svelte
<script lang="ts">
  import { createLikftc } from "@vp-tw/likftc/svelte";
  import { untrack } from "svelte";
  import { derived, type Readable } from "svelte/store";

  import {
    createAfterRows,
    createBeforeRows,
    type DemoFrameState,
  } from "../shared/demo.js";
  import Row from "./Row.svelte";

  let { frame }: { frame: Readable<DemoFrameState> } = $props();

  const items = untrack(() => derived(frame, (state) => state.items));
  const entries = untrack(() => createLikftc(items, { getId: (item) => item.id }));
  let beforeRows = $derived(createBeforeRows($frame));
  let afterRows = $derived(createAfterRows($frame, $entries));
</script>

<div class="runtime-grid">
  <article class="runtime-panel">
    <small>WITHOUT</small>
    <h3>Logical ID key</h3>
    <ol data-list="before">
      {#each beforeRows as row (row.key)}
        <Row {row} />
      {/each}
    </ol>
  </article>
  <article class="runtime-panel">
    <small>WITH @LIKFTC/SVELTE</small>
    <h3>Presence identity</h3>
    <ol data-list="after">
      {#each afterRows as row (row.key)}
        <Row {row} />
      {/each}
    </ol>
  </article>
</div>
